version: '3.8'

services:
  vespa-text:
    image: docudive/vespa_index:v1.0.0.3
    container_name: vespa-text
    ports:
      - "19101:8080"    # HTTP API
      - "19102:19071"  # Admin interface
    volumes:
      - ./app:/app
      - ./vespa-data:/opt/vespa/var
      - ./vespa-logs:/opt/vespa/logs
