version: '3.8'
services:
  vespa-single:
    image: docudive/vespa_index:v1.0.0.3
    container_name: vespa-single
    ports:
      - "2921:8081"  # HTTP API
      - "2922:19071" # Vespa admin port
      - "2923:8080"
        #environment:
        #- VESPA_CONFIGSERVER_JVMARGS=-Xms512m -Xmx512m
        #   - VESPA_CONFIGPROXY_JVMARGS=-Xms256m -Xmx256m
    volumes:
      - ./vespa-logs:/opt/vespa/var
      - ./app:/app
      - ./vespa-data:/data
    restart: unless-stopped
    networks:
      - vespa-net

  vespa-app:
    image:
      build:
        context: ./app
        dockerfile: Dockerfile
    container_name: vespa-app
    ports:
      - "11310:8000"
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - vespa-net

networks:
  vespa-net:
    driver: bridge